name: CI
on:
  push:
    branches:
      - main
    tags:
      - '*.*.*'
    pull_request:
      branches:
        - 'main'
    paths-ignore:
        - '**/README.md'

env:
  REGISTRY: ghcr.io
  NODE_IMAGE_NAME: ${{ github.repository_owner }}/kyve-${{ matrix.kyve-integration }}-node

jobs:

  pre-build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - kyve-integration: "evm"
            kyve-integration-version: v1.0.5
          - kyve-integration: "zilliqa"
            kyve-integration-version: v0.0.0
          - kyve-integration: "solana"
            kyve-integration-version: v0.0.1
          - kyve-integration: "celo"
            kyve-integration-version: v0.0.0
          - kyve-integration: "near"
            kyve-integration-version: v0.0.1
    steps:
    - uses: actions/checkout@v3
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v2.1.0
      with:
        dockerfile: Dockerfile

  kyve-integration-node:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: docker_metadata
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.NODE_IMAGE_NAME }}

    - name: Build Kyve integration node Docker image
      id: kyve_integration_build_docker_image
      uses: docker/build-push-action@v3
      with:
        build-args: |
          KYVE_INTEGRATION=${{ matrix.kyve-integration }}
          KYVE_INTEGRATION_VERSION=${{ matrix.kyve-integration-version }}
        load: true
        target: kyve-integration-node
        tags: ${{ env.NODE_IMAGE_NAME }}

    - name: Test built image using Container Structure Tests Kyve integration node Docker image
      uses: brpaz/structure-tests-action@v1.1.2
      with:
        image: ${{ env.NODE_IMAGE_NAME }}
        configFile: tests/kyve-${{ matrix.kyve-integration }}-config.yml

    - name: Analyze built image using Dive
      uses: yuichielectric/dive-action@0.0.4
      with:
        image: ${{ env.NODE_IMAGE_NAME }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for image vulnerabilities using Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.NODE_IMAGE_NAME }}
        format: table
        exit-code: 1
        ignore-unfixed: true
        severity: CRITICAL

    - name: Smoke tests
      run: docker run --rm -t ${{ env.NODE_IMAGE_NAME }} --version

    - name: Push Kyve integration node Docker image
      id: kyve_integration_push_docker_image
      uses: docker/build-push-action@v3
      with:
        push: true
        target: kyve-integration-node
        tags: ${{ steps.docker_metadata.outputs.tags }}-${{ matrix.kyve-integration }}-${{ matrix.kyve-integration-version }}
        labels: ${{ steps.docker_metadata.outputs.labels }}
